name: Build and Test Muduo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ \
            cmake \
            make \
            vim \
            wget \
            git \
            protobuf-compiler libunwind-dev libprotoc-dev \
            libgoogle-perftools-dev \
            libc-ares-dev libcurl4-openssl-dev

      - name: Add and initialize submodules
        run: |
          echo "Current Dir " pwd
          git submodule add https://github.com/google/googletest.git submodules/googletest
          git submodule add https://github.com/boostorg/boost.git submodules/boost
          git submodule update --init --recursive

      - name: Check submodule download
        run: |
          # Check googletest
          if [ ! -d "submodules/googletest" ] || [ -z "$(ls -A submodules/googletest)" ]; then
            echo "Error: googletest submodule not downloaded correctly."
            exit 1
          else
            echo "googletest submodule downloaded successfully."
          fi

          # Check boost
          if [ ! -d "submodules/boost" ] || [ -z "$(ls -A submodules/boost)" ]; then
            echo "Error: boost submodule not downloaded correctly."
            exit 1
          else
            echo "boost submodule downloaded successfully."
          fi

      - name: Build Boost
        run: |
          cd submodules/boost
          ./bootstrap.sh
          ./b2 install --prefix=../../submodules/boost_installed
          cd ../..    

      - name: Build GTest
        run: |
          mkdir -p submodules/googletest/build
          cd submodules/googletest/build
          cmake ..
          make
          make install --prefix=../../submodules/gtest_installed
          cd ../../..
      
      - name: Check Boost Installed
        run: |
          if [ ! -d "submodules/boost_installed" ] || [ -z "$(ls -A submodules/boost_installed)" ]; then
            echo "Error: Boost not installed correctly."
            exit 1
          else
            echo "Boost installed successfully."
          fi    
          
      - name: Check GTest Installed
        run: |
          if [ ! -d "submodules/gtest_installed" ] || [ -z "$(ls -A submodules/gtest_installed)" ]; then
            echo "Error: GTest not installed correctly."
            exit 1
          else
            echo "GTest installed successfully."
          fi          

      
