name: Build and Test Muduo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ \
            cmake \
            make \
            vim \
            wget \
            git \
            protobuf-compiler libunwind-dev libprotoc-dev \
            libgoogle-perftools-dev \
            libc-ares-dev libcurl4-openssl-dev \
            libgtest-dev \
            libgmock-dev \
            libboost-all-dev        

      - name: Find boost library path
        run: |
          BOOST_INCLUDE_PATH=$(find /usr/include -name boost | head -n 1)
          BOOST_LIB_PATH=$(find /usr/lib -name libboost_system.so | xargs dirname | head -n 1)
          echo "BOOST_INCLUDE_PATH=$BOOST_INCLUDE_PATH" >> $GITHUB_ENV
          echo "BOOST_LIB_PATH=$BOOST_LIB_PATH" >> $GITHUB_ENV

          ls $BOOST_INCLUDE_PATH/*
          ls $BOOST_LIB_PATH/*

      - name: Find gtest library path
        run: |
          GTEST_LIB_PATH=$(find /usr/lib -name libgtest.a)
          echo "GTEST_LIB_PATH=$GTEST_LIB_PATH" >> $GITHUB_ENV

          ls $GTEST_LIB_PATH/*

      - name: Find gmock library path
        run: |
          GMOCK_LIB_PATH=$(find /usr/lib -name libgmock.a)
          GMOCK_MAIN_LIB_PATH=$(find /usr/lib -name libgmock_main.a)
          echo "GMOCK_LIB_PATH=$GMOCK_LIB_PATH" >> $GITHUB_ENV
          echo "GMOCK_MAIN_LIB_PATH=$GMOCK_MAIN_LIB_PATH" >> $GITHUB_ENV
          
          ls $GMOCK_LIB_PATH/*
          ls $GMOCK_MAIN_LIB_PATH/*
          

      
